from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import (
    GetCountyView, FarmYearCreateView, FarmYearDeleteView, FarmYearUpdateView,
    FarmYearDetailView, FarmYearFarmCropListView, FarmYearMarketCropListView,
    FarmYearFsaCropListView, FarmCropUpdateView, MarketCropUpdateView,
    FsaCropUpdateView, FarmCropAddBudgetView, FarmYearFarmBudgetCropListView,
    FarmBudgetCropUpdateView, DetailedBudgetView, SensitivityTableView,
    FarmYearDashboard, FarmCropDeleteBudgetView, FarmYearUpdateBaselineView,
    FarmYearConfirmBaselineUpdate, BudgetPdfView)

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('farmyears/', login_required(views.farmyears), name='farmyears'),
    path('dashboard/<int:pk>', login_required(FarmYearDashboard.as_view()),
         name='dashboard'),
    path('farmyear/<int:pk>', login_required(FarmYearDetailView.as_view()),
         name='farmyear_detail'),
    path('farmyear/create', login_required(FarmYearCreateView.as_view()),
         name='farmyear_create'),
    path('farmyear/update/<int:pk>', login_required(FarmYearUpdateView.as_view()),
         name='farmyear_update'),
    path('farmyear/delete/<int:pk>', login_required(FarmYearDeleteView.as_view()),
         name='farmyear_delete'),
    path('farmyear/counties_for_state/<int:state_id>',
         login_required(GetCountyView.as_view())),
    path('farmcrops/<int:farmyear>', login_required(FarmYearFarmCropListView.as_view()),
         name='farmcrop_list'),
    path('farmbudgetcrops/<int:farmyear>',
         login_required(FarmYearFarmBudgetCropListView.as_view()),
         name='farmbudgetcrop_list'),
    path('farmbudgetcrop/update/<int:pk>',
         login_required(FarmBudgetCropUpdateView.as_view()),
         name='farmbudgetcrop_update'),
    path('farmcrop/update/<int:pk>', login_required(FarmCropUpdateView.as_view()),
         name='farmcrop_update'),
    path('marketcrops/<int:farmyear>',
         login_required(FarmYearMarketCropListView.as_view()), name='marketcrop_list'),
    path('marketcrop/update/<int:pk>', login_required(MarketCropUpdateView.as_view()),
         name='marketcrop_update'),
    path('fsacrops/<int:farmyear>', login_required(FarmYearFsaCropListView.as_view()),
         name='fsacrop_list'),
    path('fsacrop/update/<int:pk>', login_required(FsaCropUpdateView.as_view()),
         name='fsacrop_update'),
    path('farmcrops/addbudget/',
         login_required(FarmCropAddBudgetView.as_view()), name='addbudget'),
    path('farmcrops/deletebudget/',
         login_required(FarmCropDeleteBudgetView.as_view()), name='deletebudget'),
    path('detailedbudget/<int:farmyear>',
         login_required(DetailedBudgetView.as_view()), name='detailedbudget'),
    path('downloadbudget/<int:farmyear>',
         login_required(BudgetPdfView.as_view()), name='downloadbudget'),
    path('updatebaseline/',
         login_required(FarmYearUpdateBaselineView.as_view()), name='updatebaseline'),
    path('farmyear/confirmbaseline/<int:farmyear>',
         login_required(FarmYearConfirmBaselineUpdate.as_view()),
         name='confirmbaselineupdate'),
    path('sensitivity/<int:farmyear>',
         login_required(SensitivityTableView.as_view()), name='sensitivity'),
]
