# Generated by Django 6.0.6 on 2026-07-08 21:28

import datetime
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import main.models.farm_year
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ext', '0012_harvdiscoveryprices_projdiscoveryprices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=60)),
                ('county_code', models.SmallIntegerField(help_text='The county where most farm acres are located', verbose_name='primary county')),
                ('crop_year', models.SmallIntegerField(default=main.models.farm_year.get_current_year)),
                ('cropland_acres_owned', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)])),
                ('variable_rented_acres', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)], verbose_name='variable rent acres')),
                ('cash_rented_acres', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)], verbose_name='straight cash rent acres')),
                ('var_rent_cap_floor_frac', models.FloatField(default=0, help_text='Floor and cap on variable rent as a percent of starting base rent', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1, message='Ensure this value is less than or equal to 100')], verbose_name='variable rent floor/cap')),
                ('annual_land_int_expense', models.FloatField(default=0, help_text='Annual owned land interest expense in dollars', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)], verbose_name='land interest expense')),
                ('annual_land_principal_pmt', models.FloatField(default=0, help_text='Annual owned land principal payment in dollars', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)], verbose_name='land principal payment')),
                ('property_taxes', models.FloatField(default=0, help_text='Annual property taxes in dollars', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('land_repairs', models.FloatField(default=0, help_text='Annual land repair costs in dollars', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('eligible_persons_for_cap', models.SmallIntegerField(default=1, help_text='Number of eligible entities for FSA payment cap', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='# entities for FSA cap')),
                ('other_nongrain_income', models.FloatField(default=0, help_text='Other non-grain revenue in dollars', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)], verbose_name='other nongrain revenue')),
                ('other_nongrain_expense', models.FloatField(default=0, help_text='Other non-grain expense in dollars', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('manual_model_run_date', models.DateField(default=datetime.datetime.today, help_text='Manually-set date for which "current" futures prices<br>and other date-specific values are looked up.')),
                ('is_model_run_date_manual', models.BooleanField(default=False, help_text='Use the manually-set model run date (advanced).')),
                ('first_date', models.DateField(default=main.models.farm_year.default_start_date)),
                ('basis_increment', models.FloatField(default=0.1, help_text='increment to noncontract basis for basis sensitivity<br>Set to zero to turn off basis sensitivity.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0.5)])),
                ('sensitivity_data', models.JSONField(blank=True, null=True)),
                ('sensitivity_diff', models.JSONField(blank=True, null=True)),
                ('sensitivity_text', models.JSONField(blank=True, null=True)),
                ('est_sequest_frac', models.FloatField(default=0.057, help_text='Estimated reduction to computed total pre-cap title payment', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0.1, message='Ensure this value is less than or equal to 10')], verbose_name='estimated sequestration percent')),
                ('current_budget_data', models.JSONField(blank=True, null=True)),
                ('baseline_budget_data', models.JSONField(blank=True, null=True)),
                ('budget_text', models.JSONField(blank=True, null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.state')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_years', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-crop_year', 'farm_name'],
            },
        ),
        migrations.CreateModel(
            name='FarmCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planted_acres', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)])),
                ('appr_yield', models.FloatField(default=0, help_text='Approved yield provided by insurer, based on selections of YE/TA.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(400)], verbose_name='Approved yield')),
                ('adj_yield', models.FloatField(default=0, help_text='Adjusted yield provided by insurer.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(400)], verbose_name='Adjusted yield')),
                ('rate_yield', models.FloatField(default=0, help_text='Rate yield provided by insurer.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(400)])),
                ('ye', models.BooleanField(default=False, help_text='Use yield exclusion option? (e.g. exclude 2012 yields)', verbose_name='use YE?')),
                ('ta', models.BooleanField(default=False, help_text='Use trend adjustment option? (apply a trend adjustment to yields).', verbose_name='use TA?')),
                ('ql', models.BooleanField(default=False, help_text='Apply quality loss option?', verbose_name='use QL?')),
                ('ya', models.BooleanField(default=False, help_text='Apply yield averaging option?', verbose_name='use YA?')),
                ('yc', models.BooleanField(default=False, help_text='Apply yield cup option?', verbose_name='use YC?')),
                ('subcounty', models.CharField(blank=True, choices=[('AAA', 'AAA'), ('BBB', 'BBB'), ('CCC', 'CCC'), ('DDD', 'DDD'), ('EEE', 'EEE'), ('FFF', 'FFF'), ('GGG', 'GGG'), ('HHH', 'HHH'), ('III', 'III'), ('JJJ', 'JJJ'), ('LLL', 'LLL'), ('MMM', 'MMM'), ('NNN', 'NNN'), ('PPP', 'PPP'), ('QQQ', 'QQQ'), ('RRR', 'RRR'), ('URA', 'URA'), ('VVV', 'VVV'), ('SSS', 'SSS'), ('TTT', 'TTT')], default='', help_text='Primary risk class (subcounty ID) provided by crop insurer', max_length=8, verbose_name='risk class')),
                ('coverage_type', models.SmallIntegerField(blank=True, choices=[(0, 'County'), (1, 'Farm')], help_text='Crop insurance coverage type.', null=True)),
                ('product_type', models.SmallIntegerField(blank=True, choices=[(0, 'RP'), (1, 'RP-HPE'), (2, 'YP')], help_text='Crop insurance product type.', null=True)),
                ('base_coverage_level', models.FloatField(blank=True, choices=[(0.5, '50%'), (0.55, '55%'), (0.6, '60%'), (0.65, '65%'), (0.7, '70%'), (0.75, '75%'), (0.8, '80%'), (0.85, '85%'), (0.9, '90%')], help_text='Coverage level for selected crop insurance product.', null=True)),
                ('sco_use', models.BooleanField(default=False, help_text='Add Supplemental coverage option to bring coverage level to 86%?', verbose_name='add SCO option?')),
                ('eco_level', models.FloatField(blank=True, choices=[(0.9, '90%'), (0.95, '95%')], help_text='Enhanced coverage level', null=True, verbose_name='ECO level')),
                ('prot_factor', models.FloatField(default=1, help_text='Selected percent payment factor for county premiums/indemnities.', validators=[django.core.validators.MinValueValidator(0.8, message='Ensure this value is greater than or equal to 80'), django.core.validators.MaxValueValidator(1.2, message='Ensure this value is less than or equal to 120')], verbose_name='selected payment factor')),
                ('crop_ins_prems', models.JSONField(blank=True, null=True)),
                ('ins_practice', models.SmallIntegerField(choices=[(2, 'Irrigated'), (3, 'Non-Irrigated'), (53, 'Non-Irrigated'), (43, 'Non-Irrigated'), (94, 'Irrigated'), (95, 'Irrigated')], verbose_name='Irrigated?')),
                ('ins_practices', django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), null=True)),
                ('prems_computed_for', models.DateField(null=True)),
                ('proj_price_disc_start', models.DateField(null=True)),
                ('proj_price_disc_end', models.DateField(null=True)),
                ('harv_price_disc_start', models.DateField(null=True)),
                ('harv_price_disc_end', models.DateField(null=True)),
                ('cty_yield_final', models.DateField(null=True)),
                ('farm_crop_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.farmcroptype')),
                ('ins_crop_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_crop_types', to='ext.inscroptype')),
                ('farm_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_crops', to='main.farmyear')),
            ],
            options={
                'ordering': ['farm_crop_type_id'],
            },
        ),
        migrations.CreateModel(
            name='FarmBudgetCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_yield', models.FloatField(default=0, help_text='Set this to the final farm yield after harvest', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(400)])),
                ('county_yield', models.FloatField(default=0, help_text='Set this to the estimated final county yield after harvest', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(400)])),
                ('description', models.CharField(max_length=50)),
                ('yield_variability', models.FloatField(default=0, help_text='Percent of nonland cost assumed to depend on yield', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1, message='Ensure this value is greater than or equal to 100')])),
                ('other_gov_pmts', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)])),
                ('other_revenue', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('fertilizers', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('pesticides', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('seed', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('drying', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('storage', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('other_direct_costs', models.FloatField(default=0, help_text='Other (hauling, custom operations)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('machine_hire_lease', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)], verbose_name='machine hire or lease')),
                ('utilities', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('machine_repair', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('fuel_and_oil', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('light_vehicle', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('machine_depr', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)], verbose_name='machine depreciation')),
                ('labor_and_mgmt', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)], verbose_name='labor and management')),
                ('building_repair_and_rent', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('building_depr', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)], verbose_name='building depreciation')),
                ('insurance', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('misc_overhead_costs', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('interest_nonland', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)], verbose_name='non-land interest cost')),
                ('other_overhead_costs', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('rented_land_costs', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999)])),
                ('is_rot', models.BooleanField(null=True)),
                ('is_irr', models.BooleanField(default=False)),
                ('budget_date', models.DateField(null=True)),
                ('baseline_yield_for_var_rent', models.FloatField(default=0, help_text='Fixed farm yield used for variable rent and yield-based cost adjustment', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(400)], verbose_name='baseline yield')),
                ('is_farm_yield_final', models.BooleanField(default=False, help_text='Adjust expected yield(s) and check this box after harvest', verbose_name='Are yields final?')),
                ('yield_factor', models.FloatField(default=1, help_text='Percent of expected yield(s) assesed prior to harvest, affecting detailed budget', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2, message='Ensure this value is less than or equal to 200')], verbose_name='yield sensititivity factor')),
                ('are_costs_final', models.BooleanField(default=False, help_text='Adjust costs and check this box (if desired) once costs are known', verbose_name='Costs final?')),
                ('budget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ext.budget')),
                ('budget_crop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ext.budgetcrop')),
                ('farm_crop_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ext.farmcroptype')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farm_budget_crops', to='ext.state')),
                ('farm_crop', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.farmcrop')),
                ('farm_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.farmyear')),
            ],
            options={
                'ordering': ['farm_crop_type_id'],
            },
        ),
        migrations.CreateModel(
            name='FsaCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plc_base_acres', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)], verbose_name='Base acres in PLC')),
                ('arcco_base_acres', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)], verbose_name='Base acres in ARC-CO')),
                ('plc_yield', models.FloatField(default=0, help_text='Weighted average PLC yield for farm in bushels per acre.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(400)], verbose_name='farm avg. PLC yield')),
                ('effective_ref_price', models.FloatField(null=True)),
                ('natl_loan_rate', models.FloatField(null=True)),
                ('farm_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fsa_crops', to='main.farmyear')),
                ('fsa_crop_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.fsacroptype')),
            ],
            options={
                'ordering': ['fsa_crop_type_id'],
            },
        ),
        migrations.CreateModel(
            name='MarketCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assumed_basis_for_new', models.FloatField(default=0, help_text='Assumed basis for non-contracted bushels.', validators=[django.core.validators.MinValueValidator(-2), django.core.validators.MaxValueValidator(2)])),
                ('price_factor', models.FloatField(default=1, help_text='Percent of current futures price, reflected in detailed budget', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10, message='Ensure this value is less than or equal to 1000')], verbose_name='price sensititivity factor')),
                ('farm_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_crops', to='main.farmyear')),
                ('fsa_crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_crops', to='main.fsacrop')),
                ('market_crop_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.marketcroptype')),
            ],
            options={
                'ordering': ['market_crop_type_id'],
            },
        ),
        migrations.AddField(
            model_name='farmcrop',
            name='market_crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_crops', to='main.marketcrop'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_date', models.DateField(default=datetime.datetime.today)),
                ('bushels', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999)])),
                ('futures_price', models.FloatField(blank=True, null=True, verbose_name='futures price per bushel')),
                ('basis_price', models.FloatField(blank=True, null=True, verbose_name='basis price per bushel')),
                ('terminal', models.CharField(blank=True, max_length=60)),
                ('contract_number', models.CharField(blank=True, max_length=25)),
                ('delivery_start_date', models.DateField(blank=True, null=True)),
                ('delivery_end_date', models.DateField(blank=True, null=True)),
                ('market_crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='main.marketcrop')),
            ],
            options={
                'ordering': ['contract_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='farmyear',
            constraint=models.UniqueConstraint(models.F('farm_name'), models.F('user'), models.F('crop_year'), name='farm_name_unique_for_user_crop_year'),
        ),
    ]
