# Generated by Django 4.2 on 2023-05-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HarvestFuturesPrice',
            new_name='FuturesPrice',
        ),
        migrations.AddField(
            model_name='farmcrop',
            name='new_crop_ticker',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='farmcrop',
            name='new_crop_fut_harv_price',
            field=models.FloatField(default=0, help_text='Current new crop futures harvest price.', verbose_name='new crop futures price'),
        ),
    ]
