# Generated by Django 4.2 on 2023-05-02 23:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmcrop',
            name='subcounty',
            field=models.ForeignKey(blank=True, help_text='Primary risk class (subcounty ID) provided by crop insurer', null=True, on_delete=django.db.models.deletion.CASCADE, to='ext.subcounty', verbose_name='risk class'),
        ),
        migrations.AlterField(
            model_name='farmyear',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.budget'),
        ),
        migrations.AlterField(
            model_name='harvestfuturesprice',
            name='priced_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
