# Generated by Django 4.2 on 2023-05-02 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_farmcrop_subcounty_alter_farmyear_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricedcrop',
            name='new_crop_fut_harv_price',
            field=models.ForeignKey(blank=True, help_text='Current new crop futures harvest price.', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.harvestfuturesprice', verbose_name='new crop futures price'),
        ),
    ]
