# Generated by Django 4.2 on 2023-05-15 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_farmcrop_nonrotating_acres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmcrop',
            name='frac_yield_dep_nonland_cost',
            field=models.FloatField(default=0.2, help_text='Estimated % of non-land costs that vary with yield.', verbose_name='est. % yield-dependent cost'),
        ),
    ]
