# Generated by Django 4.2 on 2023-05-07 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_harvestfuturesprice_futuresprice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyaPostEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_year', models.SmallIntegerField()),
                ('forecast_month', models.CharField(max_length=8)),
                ('wasde_release_date', models.DateField(verbose_name='WASDE release date')),
                ('wasde_estimated_price', models.FloatField(null=True)),
                ('assumed_pct_locked', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MyaPreEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_year', models.SmallIntegerField()),
                ('month', models.SmallIntegerField()),
                ('year', models.SmallIntegerField()),
                ('actual_farm_price', models.FloatField(null=True)),
                ('nearby_futures_month', models.CharField(max_length=8)),
                ('five_year_avg_basis', models.FloatField()),
                ('five_year_avg_weight', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='farmyear',
            name='price_factor',
            field=models.FloatField(default=1, verbose_name='price sensititivity factor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmyear',
            name='yield_factor',
            field=models.FloatField(default=1, verbose_name='yield sensititivity factor'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='futuresprice',
            index=models.Index(models.F('croptype'), models.F('futures_month'), models.F('priced_on'), name='fut_price_croptype_mth_pron'),
        ),
        migrations.AddIndex(
            model_name='futuresprice',
            index=models.Index(models.F('market_crop_type'), models.F('futures_month'), models.F('priced_on'), name='fut_price_mktcroptype_mth_pron'),
        ),
        migrations.AddField(
            model_name='myapreestimate',
            name='fsa_crop_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fsacroptype'),
        ),
        migrations.AddField(
            model_name='myapostestimate',
            name='fsa_crop_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fsacroptype'),
        ),
    ]
