# Generated by Django 4.2 on 2023-05-03 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_pricedcrop_new_crop_fut_harv_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmcrop',
            name='ins_practice',
            field=models.SmallIntegerField(),
        ),
    ]
