# Generated by Django 4.2 on 2023-05-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_myapostestimate_myapreestimate_farmyear_price_factor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmyear',
            name='price_factor',
            field=models.FloatField(default=1, verbose_name='price sensititivity factor'),
        ),
        migrations.AlterField(
            model_name='farmyear',
            name='yield_factor',
            field=models.FloatField(default=1, verbose_name='yield sensititivity factor'),
        ),
    ]
