# Generated by Django 4.2 on 2023-05-03 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_farmcrop_ins_practice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmcrop',
            name='base_coverage_level',
            field=models.DecimalField(blank=True, choices=[(0.5, '50%'), (0.55, '55%'), (0.6, '60%'), (0.65, '65%'), (0.7, '70%'), (0.75, '75%'), (0.8, '80%'), (0.85, '85%')], decimal_places=2, help_text='Coverage level for selected crop insurance product.', max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='farmcrop',
            name='coverage_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'County (area)'), (1, 'Farm (enterprise)')], help_text='Crop insurance coverage type.', null=True),
        ),
        migrations.AlterField(
            model_name='farmcrop',
            name='crop_ins_prems',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmcrop',
            name='eco_level',
            field=models.DecimalField(blank=True, choices=[(0.9, '90%'), (0.95, '95%')], decimal_places=2, help_text='Enhanced coverage level', max_digits=2, null=True, verbose_name='ECO level'),
        ),
        migrations.AlterField(
            model_name='farmcrop',
            name='price_vol_factor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated price volatility factor', max_digits=2, null=True, verbose_name='price volatility factor'),
        ),
        migrations.AlterField(
            model_name='farmcrop',
            name='product_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'RP'), (1, 'RP-HPE'), (2, 'YP')], help_text='Crop insurance product type.', null=True),
        ),
        migrations.AlterField(
            model_name='farmcrop',
            name='proj_harv_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimate for projected harvest price', max_digits=4, null=True, verbose_name='projected harvest price'),
        ),
    ]
