# Generated by Django 4.2 on 2023-05-21 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0001_initial'),
        ('main', '0004_rename_assumed_basis_farmbudgetcrop_yield_variability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmbudgetcrop',
            name='budget_crop_type',
        ),
        migrations.AddField(
            model_name='farmbudgetcrop',
            name='farm_crop_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ext.farmcroptype'),
        ),
        migrations.AddField(
            model_name='farmbudgetcrop',
            name='is_irr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmbudgetcrop',
            name='is_rot',
            field=models.BooleanField(null=True),
        ),
    ]
