# Generated by Django 4.2 on 2023-05-21 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0001_initial'),
        ('main', '0005_remove_farmbudgetcrop_budget_crop_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baselinefarmbudgetcrop',
            name='budget_crop_type',
        ),
        migrations.AddField(
            model_name='baselinefarmbudgetcrop',
            name='farm_crop_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ext.farmcroptype'),
            preserve_default=False,
        ),
    ]
