# Generated by Django 4.2 on 2023-05-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_farmcrop_base_coverage_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmyear',
            name='is_baseline',
            field=models.BooleanField(default=False),
        ),
    ]
