# Generated by Django 4.2.1 on 2023-05-22 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0002_delete_budgetcroptype'),
        ('main', '0006_remove_baselinefarmbudgetcrop_budget_crop_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmbudgetcrop',
            old_name='orig_budget',
            new_name='budget',
        ),
        migrations.RemoveField(
            model_name='farmbudgetcrop',
            name='farm_crop',
        ),
        migrations.AddField(
            model_name='farmcrop',
            name='farm_budget_crop',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.farmbudgetcrop'),
        ),
        migrations.AlterField(
            model_name='farmbudgetcrop',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farm_budget_crops', to='ext.state'),
        ),
    ]
