# Generated by Django 4.2 on 2023-05-03 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_farmyear_is_baseline'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetcrop',
            name='orig_budget_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='budgetcroptype',
            name='is_irr',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='farmcrop',
            name='frac_yield_dep_nonland_cost',
            field=models.FloatField(blank=True, help_text='Estimated % of non-land costs that vary with yield.', null=True, verbose_name='est. % yield-dependent cost'),
        ),
        migrations.AlterField(
            model_name='farmcrop',
            name='rotating_acres',
            field=models.FloatField(blank=True, help_text='The number of rotating acres, e.g. corn on beans.', null=True),
        ),
    ]
