# Generated by Django 4.2 on 2023-05-04 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_budgetcrop_orig_budget_id_budgetcroptype_is_irr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetcrop',
            name='orig_budget_id',
        ),
        migrations.AddField(
            model_name='budgetcrop',
            name='orig_budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orig_budget', to='main.budget'),
        ),
        migrations.AddField(
            model_name='farmyear',
            name='master_farm_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.farmyear'),
        ),
    ]
