# Generated by Django 4.2.1 on 2023-05-22 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_orig_budget_farmbudgetcrop_budget_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmcrop',
            name='farm_budget_crop',
        ),
        migrations.AddField(
            model_name='farmbudgetcrop',
            name='farm_crop',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farm_budget_crop', to='main.farmcrop'),
        ),
    ]
