# Generated by Django 4.2.1 on 2023-05-27 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_farmcrop_farm_budget_crop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmbudgetcrop',
            name='farm_crop',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.farmcrop'),
        ),
    ]
