# Generated by Django 4.2.1 on 2023-05-30 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_farmbudgetcrop_farm_crop'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmbudgetcrop',
            name='farm_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.farmyear'),
        ),
    ]
