# Generated by Django 4.2.1 on 2023-05-30 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0003_alter_budgetcrop_options'),
        ('main', '0010_farmbudgetcrop_farm_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmbudgetcrop',
            name='budget_crop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ext.budgetcrop'),
        ),
    ]
