# Generated by Django 4.2.1 on 2023-06-04 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_farmbudgetcrop_building_depr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmcrop',
            name='prems_computed_for',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='farmyear',
            name='model_run_date',
            field=models.DateField(default=datetime.datetime.today, help_text='The date for which "current" futures prices and other date-specific values are looked up.'),
        ),
    ]
