# Generated by Django 4.2.1 on 2023-06-04 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_farmcrop_prems_computed_for_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='farmcrop',
            name='prot_factor_in_range',
        ),
        migrations.RemoveField(
            model_name='farmcrop',
            name='rma_cty_expected_yield',
        ),
    ]
