# Generated by Django 4.2.1 on 2023-06-15 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_farmcrop_prot_factor_in_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmcrop',
            name='cty_yield_final',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='farmcrop',
            name='harv_price_disc_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='farmcrop',
            name='proj_price_disc_end',
            field=models.DateField(null=True),
        ),
    ]
