# Generated by Django 4.2.1 on 2023-06-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_farmcrop_cty_yield_final_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmbudgetcrop',
            options={'ordering': ['farm_crop_type_id']},
        ),
        migrations.AlterModelOptions(
            name='farmcrop',
            options={'ordering': ['farm_crop_type_id']},
        ),
        migrations.AlterModelOptions(
            name='farmyear',
            options={'ordering': ['-crop_year', 'farm_name']},
        ),
        migrations.AlterModelOptions(
            name='fsacrop',
            options={'ordering': ['fsa_crop_type_id']},
        ),
        migrations.AlterModelOptions(
            name='marketcrop',
            options={'ordering': ['market_crop_type_id']},
        ),
        migrations.RemoveField(
            model_name='farmcrop',
            name='gov_pmt_portion',
        ),
        migrations.AddField(
            model_name='farmcrop',
            name='benchmark_revenue',
            field=models.FloatField(null=True),
        ),
    ]
