# Generated by Django 4.2.2 on 2023-06-19 16:23

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_farmbudgetcrop_options_alter_farmcrop_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmyear',
            name='model_run_date',
        ),
        migrations.AddField(
            model_name='farmyear',
            name='manual_model_run_date',
            field=models.DateField(default=datetime.datetime.today, help_text='Manually-set date for which "current" futures prices and other date-specific values are looked up.'),
        ),
        migrations.AlterField(
            model_name='farmyear',
            name='eligible_persons_for_cap',
            field=models.SmallIntegerField(default=1, help_text="Number of eligible 'persons' for FSA payment caps.", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='# persons for cap'),
        ),
        migrations.AlterField(
            model_name='farmyear',
            name='is_model_run_date_manual',
            field=models.BooleanField(default=False, help_text='Use the manually-set model run date (advanced).'),
        ),
    ]
