# Generated by Django 4.2.2 on 2023-06-21 02:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_farmyear_model_run_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmyear',
            name='price_factor',
        ),
        migrations.RemoveField(
            model_name='farmyear',
            name='yield_factor',
        ),
        migrations.AddField(
            model_name='farmcrop',
            name='price_factor',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='price sensititivity factor'),
        ),
        migrations.AddField(
            model_name='farmcrop',
            name='yield_factor',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='yield sensititivity factor'),
        ),
    ]
