# Generated by Django 4.2.2 on 2023-06-21 21:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_farmyear_price_factor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmcrop',
            name='price_factor',
        ),
        migrations.AddField(
            model_name='marketcrop',
            name='price_factor',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='price sensititivity factor'),
        ),
    ]
