# Generated by Django 4.2.2 on 2023-06-23 22:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_farmcrop_price_factor_marketcrop_price_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmcrop',
            name='prot_factor',
            field=models.FloatField(default=1, help_text='Selected payment factor for county premiums/indemnities.', validators=[django.core.validators.MinValueValidator(0.8), django.core.validators.MaxValueValidator(1.2)], verbose_name='selected payment factor'),
        ),
        migrations.AlterField(
            model_name='farmyear',
            name='eligible_persons_for_cap',
            field=models.SmallIntegerField(default=1, help_text="Number of eligible 'persons' for FSA payment caps.", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='# persons for cap'),
        ),
    ]
