# Generated by Django 4.2.2 on 2023-06-24 00:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_farmcrop_prot_factor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmyear',
            name='annual_land_int_expense',
            field=models.FloatField(default=0, help_text='Annual owned land interest expense in dollars', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)], verbose_name='land interest expense'),
        ),
        migrations.AlterField(
            model_name='farmyear',
            name='annual_land_principal_pmt',
            field=models.FloatField(default=0, help_text='Annual owned land principal payment in dollars', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)], verbose_name='land principal payment'),
        ),
        migrations.AlterField(
            model_name='farmyear',
            name='land_repairs',
            field=models.FloatField(default=0, help_text='Annual land repair costs in dollars', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AlterField(
            model_name='farmyear',
            name='other_nongrain_expense',
            field=models.FloatField(default=0, help_text='Other non-grain expense in dollars', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AlterField(
            model_name='farmyear',
            name='other_nongrain_income',
            field=models.FloatField(default=0, help_text='Other non-grain income in dollars', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AlterField(
            model_name='farmyear',
            name='property_taxes',
            field=models.FloatField(default=0, help_text='Annual property taxes in dollars', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
