# Generated by Django 4.2.2 on 2023-06-27 00:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_farmyear_annual_land_int_expense_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmyear',
            name='report_type',
        ),
        migrations.AlterField(
            model_name='farmyear',
            name='manual_model_run_date',
            field=models.DateField(default=datetime.datetime.today, help_text='Manually-set date for which "current" futures prices<br>and other date-specific values are looked up.'),
        ),
    ]
