# Generated by Django 4.2.2 on 2023-07-01 18:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_farmbudgetcrop_budget_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmbudgetcrop',
            name='baseline_yield_for_var_rent',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(400)], verbose_name='baseline yield for variable rent'),
        ),
        migrations.AlterField(
            model_name='farmcrop',
            name='coverage_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'County'), (1, 'Farm')], help_text='Crop insurance coverage type.', null=True),
        ),
    ]
