# Generated by Django 4.2.2 on 2023-07-01 19:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_farmbudgetcrop_baseline_yield_for_var_rent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmyear',
            name='cropland_acres_rented',
        ),
        migrations.AddField(
            model_name='farmyear',
            name='variable_rented_acres',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)], verbose_name='variable rent acres'),
        ),
        migrations.AlterField(
            model_name='farmyear',
            name='cash_rented_acres',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)], verbose_name='straight cash rent acres'),
        ),
    ]
