# Generated by Django 4.2.2 on 2023-07-01 20:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_remove_farmyear_cropland_acres_rented_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmyear',
            name='eligible_persons_for_cap',
            field=models.SmallIntegerField(default=1, help_text='Number of eligible entities for FSA payment cap', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='# entities for FSA cap'),
        ),
    ]
