# Generated by Django 4.2.2 on 2023-07-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_farmbudgetcrop_farm_yield_final_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmbudgetcrop',
            name='farm_yield_final_on',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='farmbudgetcrop',
            name='is_farm_yield_final',
            field=models.BooleanField(default=False, help_text='Adjust the farm yield and check this box once farm yield is known', verbose_name='farm yield final?'),
        ),
    ]
