# Generated by Django 4.2.2 on 2023-07-03 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_farmbudgetcrop_farm_yield_final_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmcrop',
            name='yield_factor',
        ),
        migrations.AddField(
            model_name='farmbudgetcrop',
            name='yield_factor',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='yield sensititivity factor'),
        ),
    ]
