# Generated by Django 4.2.2 on 2023-07-03 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_remove_farmcrop_yield_factor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmbudgetcrop',
            name='baseline_yield_for_var_rent',
            field=models.FloatField(default=0, help_text='Fixed yield used for variable rent and yield-based cost adjustment', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(400)], verbose_name='baseline yield'),
        ),
        migrations.AlterField(
            model_name='farmbudgetcrop',
            name='farm_yield',
            field=models.FloatField(default=0, help_text='Set this to the final yield after harvest', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(400)]),
        ),
        migrations.AlterField(
            model_name='farmbudgetcrop',
            name='yield_factor',
            field=models.FloatField(default=1, help_text='Modify expected yields prior to harvest, affecting detailed budget', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='yield sensititivity factor'),
        ),
    ]
