# Generated by Django 4.2.2 on 2023-07-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_farmbudgetcrop_baseline_yield_for_var_rent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmbudgetcrop',
            name='farm_yield_final_on',
        ),
        migrations.AddField(
            model_name='farmbudgetcrop',
            name='are_costs_final',
            field=models.BooleanField(default=False, help_text='Adjust costs and check this box (if desired) once costs are known', verbose_name='Costs final?'),
        ),
    ]
