# Generated by Django 4.2.2 on 2023-07-05 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_remove_farmbudgetcrop_farm_yield_final_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmyear',
            name='est_sequest_frac',
            field=models.FloatField(default=0.062),
        ),
        migrations.AddField(
            model_name='fsacrop',
            name='effective_ref_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='fsacrop',
            name='natl_loan_rate',
            field=models.FloatField(null=True),
        ),
    ]
