# Generated by Django 4.2.3 on 2023-07-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_farmbudgetcrop_is_farm_yield_final_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baselinefarmcrop',
            name='farm_crop_type',
        ),
        migrations.RemoveField(
            model_name='baselinefarmcrop',
            name='farm_year',
        ),
        migrations.RemoveField(
            model_name='baselinefarmcrop',
            name='market_crop',
        ),
        migrations.RemoveField(
            model_name='baselinefarmyear',
            name='farm_year',
        ),
        migrations.RemoveField(
            model_name='baselinefsacrop',
            name='farm_year',
        ),
        migrations.RemoveField(
            model_name='baselinefsacrop',
            name='fsa_crop_type',
        ),
        migrations.RemoveField(
            model_name='baselinemarketcrop',
            name='farm_year',
        ),
        migrations.RemoveField(
            model_name='baselinemarketcrop',
            name='fsa_crop',
        ),
        migrations.RemoveField(
            model_name='baselinemarketcrop',
            name='market_crop_type',
        ),
        migrations.AddField(
            model_name='farmyear',
            name='benchmark_budget_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='BaselineFarmBudgetCrop',
        ),
        migrations.DeleteModel(
            name='BaselineFarmCrop',
        ),
        migrations.DeleteModel(
            name='BaselineFarmYear',
        ),
        migrations.DeleteModel(
            name='BaselineFsaCrop',
        ),
        migrations.DeleteModel(
            name='BaselineMarketCrop',
        ),
    ]
