# Generated by Django 4.2.4 on 2023-09-13 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_rename_benchmark_budget_data_farmyear_baseline_budget_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmyear',
            name='other_nongrain_income',
            field=models.FloatField(default=0, help_text='Other non-grain revenue in dollars', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)], verbose_name='other nongrain revenue'),
        ),
    ]
