# Generated by Django 4.2.5 on 2023-09-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_alter_farmyear_other_nongrain_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmyear',
            name='sensitivity_text',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
