# Generated by Django 4.2.5 on 2023-09-20 19:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_remove_marketcrop_avg_contract_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_basis', models.BooleanField(default=False, help_text='Specifies a basis contract instead of a futures contract.')),
                ('contract_date', models.DateField(default=datetime.datetime.today)),
                ('bushels', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0, verbose_name='price per bushel')),
                ('terminal', models.CharField(blank=True, max_length=60)),
                ('contract_number', models.CharField(blank=True, max_length=25)),
                ('delivery_start_date', models.DateField(blank=True, null=True)),
                ('delivery_end_date', models.DateField(blank=True, null=True)),
                ('market_crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='main.marketcrop')),
            ],
            options={
                'ordering': ['contract_date'],
            },
        ),
    ]
