# Generated by Django 4.2.5 on 2023-09-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_alter_contract_bushels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='delivery_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='delivery_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
