# Generated by Django 4.2.5 on 2023-09-23 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_alter_contract_delivery_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(-2), django.core.validators.MaxValueValidator(30)], verbose_name='price per bushel'),
        ),
    ]
