# Generated by Django 4.2.5 on 2023-10-01 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_alter_contract_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='is_basis',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='price',
        ),
        migrations.AddField(
            model_name='contract',
            name='basis_price',
            field=models.FloatField(blank=True, null=True, verbose_name='basis price per bushel'),
        ),
        migrations.AddField(
            model_name='contract',
            name='futures_price',
            field=models.FloatField(blank=True, null=True, verbose_name='futures price per bushel'),
        ),
        migrations.AddField(
            model_name='farmyear',
            name='basis_increment',
            field=models.FloatField(default=0.1, help_text='increment to noncontract basis for basis sensitivity<br>Set to zero to turn off basis sensitivity.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0.5)]),
        ),
    ]
