# Generated by Django 4.2.6 on 2023-10-13 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_remove_contract_is_basis_remove_contract_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='bushels',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
