# Generated by Django 4.2.6 on 2023-10-16 21:09

from django.db import migrations, models
import main.models.util


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_alter_contract_bushels'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmyear',
            name='first_date',
            field=models.DateField(default=main.models.util.default_start_date),
        ),
    ]
