# Generated by Django 4.2.6 on 2023-10-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_farmyear_first_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmcrop',
            name='harv_price_disc_start',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='farmcrop',
            name='proj_price_disc_start',
            field=models.DateField(null=True),
        ),
    ]
