# Generated by Django 4.2.6 on 2023-10-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_farmcrop_harv_price_disc_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmyear',
            name='sensitivity_diff',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
