# Generated by Django 4.2.7 on 2023-11-13 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_farmyear_sensitivity_diff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmcrop',
            old_name='ta_aph_yield',
            new_name='appr_yield',
        ),
    ]
