# Generated by Django 4.2 on 2023-05-02 20:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.SmallIntegerField()),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'ext_commodity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CropType',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('abbr', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'ext_commoditytype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InsurableCropsForCty',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('state_id', models.SmallIntegerField()),
                ('county_code', models.SmallIntegerField()),
                ('crop_id', models.SmallIntegerField(db_column='commodity_id')),
                ('crop_type_id', models.SmallIntegerField(db_column='commodity_type_id')),
                ('is_fac', models.BooleanField()),
                ('practices', django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), size=2)),
            ],
            options={
                'db_table': 'ext_insurable_crops_for_cty',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.SmallIntegerField()),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'ext_practice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PracticeAvail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('county_code', models.SmallIntegerField()),
                ('practice', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'ext_practiceavail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('abbr', models.CharField(max_length=2)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subcounty',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'ext_subcounty',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubcountyAvail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('county_code', models.SmallIntegerField()),
                ('practice', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'ext_subcountyavail',
                'managed': False,
            },
        ),
    ]
