# Generated by Django 4.2 on 2023-04-16 02:41

from django.db import migrations, models
import django.db.models.deletion
import ext.models


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityType',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('abbr', models.CharField(max_length=10)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.commodity')),
            ],
        ),
        migrations.CreateModel(
            name='UnitDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_discount_id', models.IntegerField()),
                ('coverage_level', ext.models.SmallFloatField(null=True)),
                ('area_low_qty', ext.models.SmallFloatField(null=True)),
                ('area_high_qty', ext.models.SmallFloatField(null=True)),
                ('enterprise_discount_factor', ext.models.SmallFloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subsidy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_structure_code', models.CharField(max_length=2, null=True)),
                ('coverage_level', ext.models.SmallFloatField()),
                ('subsidy', ext.models.SmallFloatField()),
                ('commodity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ext.commodity')),
                ('coverage_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.coveragetype')),
                ('insurance_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.insuranceplan')),
            ],
        ),
        migrations.CreateModel(
            name='SubCountyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_code', models.SmallIntegerField()),
                ('subcounty_rate', ext.models.SmallFloatField(null=True)),
                ('practice', models.SmallIntegerField()),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.commodity')),
                ('commodity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.commoditytype')),
                ('insurance_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.insuranceplan')),
                ('rate_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ext.ratemethods')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.state')),
                ('subcounty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.subcounty')),
            ],
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SmallIntegerField()),
                ('name', models.CharField(max_length=40)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.commodity')),
            ],
        ),
        migrations.CreateModel(
            name='OptionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_code', models.SmallIntegerField()),
                ('option_rate', ext.models.SmallFloatField()),
                ('practice', models.SmallIntegerField()),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.commodity')),
                ('commodity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.commoditytype')),
                ('insurance_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.insuranceoption')),
                ('insurance_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.insuranceplan')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.state')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceOffer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('county_code', models.SmallIntegerField()),
                ('beta_id', models.SmallIntegerField(null=True)),
                ('unit_discount_id', models.IntegerField(null=True)),
                ('practice', models.SmallIntegerField()),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.commodity')),
                ('commodity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.commoditytype')),
                ('insurance_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.insuranceplan')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.state')),
            ],
        ),
        migrations.CreateModel(
            name='CoverageLevelDifferential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_code', models.SmallIntegerField()),
                ('coverage_level', ext.models.SmallFloatField()),
                ('rate_differential_factor', ext.models.SmallFloatField(null=True)),
                ('enterprise_residual_factor', ext.models.SmallFloatField(null=True)),
                ('rate_differential_factor_prior', ext.models.SmallFloatField(null=True)),
                ('enterprise_residual_factor_prior', ext.models.SmallFloatField(null=True)),
                ('practice', models.SmallIntegerField()),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.commodity')),
                ('commodity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.commoditytype')),
                ('coverage_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.coveragetype')),
                ('insurance_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.insuranceplan')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.state')),
                ('subcounty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ext.subcounty')),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SmallIntegerField()),
                ('name', models.CharField(max_length=40)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.state')),
            ],
        ),
        migrations.CreateModel(
            name='ComboRevenueFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_rate', ext.models.SmallFloatField()),
                ('std_deviation_qty', ext.models.SmallFloatField()),
                ('mean_qty', ext.models.SmallFloatField()),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.commodity')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.state')),
            ],
        ),
        migrations.CreateModel(
            name='BaseRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_code', models.SmallIntegerField()),
                ('coverage_level', ext.models.SmallFloatField()),
                ('reference_rate', ext.models.SmallFloatField()),
                ('exponent', ext.models.SmallFloatField()),
                ('fixed_rate', ext.models.SmallFloatField()),
                ('reference_rate_prior', ext.models.SmallFloatField()),
                ('exponent_prior', ext.models.SmallFloatField()),
                ('fixed_rate_prior', ext.models.SmallFloatField()),
                ('practice', models.SmallIntegerField()),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.commodity')),
                ('commodity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.commoditytype')),
                ('insurance_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.insuranceplan')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.state')),
            ],
        ),
    ]
