# Generated by Django 4.2 on 2023-05-21 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BudgetCropType',
        ),
    ]
