# Generated by Django 4.2 on 2023-05-14 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoybeanInsTypeForState',
            fields=[
                ('state_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('soybean_ins_type', models.SmallIntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
    ]
