# Generated by Django 4.2.1 on 2023-05-23 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0002_delete_budgetcroptype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetcrop',
            options={'managed': False, 'ordering': ['state__abbr', 'description', 'is_rot', 'farm_yield', 'rented_land_costs']},
        ),
    ]
