# Generated by Django 4.2 on 2023-04-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0002_commoditytype_unitdiscount_subsidy_subcountyrate_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='areacoveragelevel',
            index=models.Index(fields=['area_rate_id'], name='ext_areacov_area_ra_73bf35_idx'),
        ),
    ]
