# Generated by Django 4.2 on 2023-04-16 13:47

from django.db import migrations, models
import django.db.models.deletion
import ext.models


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0003_areacoveragelevel_ext_areacov_area_ra_73bf35_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceOfferEnt',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('county_code', models.SmallIntegerField()),
                ('beta_id', models.SmallIntegerField(null=True)),
                ('unit_discount_id', models.IntegerField(null=True)),
                ('practice', models.SmallIntegerField()),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.commodity')),
                ('commodity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.commoditytype')),
                ('insurance_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.insuranceplan')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.state')),
            ],
        ),
        migrations.CreateModel(
            name='EnterpriseFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_code', models.SmallIntegerField()),
                ('coverage_level', ext.models.SmallFloatField()),
                ('enterprise_residual_factor', ext.models.SmallFloatField(null=True)),
                ('enterprise_residual_factor_prior', ext.models.SmallFloatField(null=True)),
                ('practice', models.SmallIntegerField()),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.commodity')),
                ('commodity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.commoditytype')),
                ('coverage_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.coveragetype')),
                ('insurance_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.insuranceplan')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.state')),
                ('subcounty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ext.subcounty')),
            ],
        ),
    ]
