# Generated by Django 4.2.1 on 2023-06-02 19:49

from django.db import migrations, models
import ext.models


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0003_alter_budgetcrop_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricePrevyear',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('county_code', models.SmallIntegerField()),
                ('crop_id', models.SmallIntegerField(db_column='commodity_id')),
                ('crop_type_id', models.SmallIntegerField(db_column='commodity_type_id')),
                ('state_id', models.SmallIntegerField()),
                ('projected_price', ext.models.SmallFloatField()),
                ('price_volatility_factor', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'ext_price_prevyear',
                'managed': False,
            },
        ),
    ]
