# Generated by Django 4.2.1 on 2023-06-04 23:43

from django.db import migrations, models
import ext.models


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0004_priceprevyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedYield',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('county_code', models.SmallIntegerField()),
                ('crop_id', models.SmallIntegerField(db_column='commodity_id')),
                ('crop_type_id', models.SmallIntegerField(db_column='commodity_type_id')),
                ('state_id', models.SmallIntegerField()),
                ('expected_yield', ext.models.SmallFloatField()),
            ],
            options={
                'db_table': 'ext_expectedyield',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('county_code', models.SmallIntegerField()),
                ('crop_id', models.SmallIntegerField(db_column='commodity_id')),
                ('crop_type_id', models.SmallIntegerField(db_column='commodity_type_id')),
                ('state_id', models.SmallIntegerField()),
                ('projected_price', ext.models.SmallFloatField()),
                ('price_volatility_factor', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'ext_price',
                'managed': False,
            },
        ),
    ]
