# Generated by Django 4.2 on 2023-04-16 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0004_insuranceofferent_enterprisefactor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InsuranceOffer',
            new_name='InsuranceOfferArea',
        ),
        migrations.RenameModel(
            old_name='CoverageLevelDifferential',
            new_name='RateDifferential',
        ),
    ]
