# Generated by Django 4.2 on 2023-04-16 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0005_rename_insuranceoffer_insuranceofferarea_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuranceofferarea',
            name='beta_id',
        ),
        migrations.RemoveField(
            model_name='insuranceofferarea',
            name='unit_discount_id',
        ),
        migrations.RemoveField(
            model_name='insuranceofferent',
            name='insurance_plan',
        ),
        migrations.RemoveField(
            model_name='optionrate',
            name='insurance_plan',
        ),
        migrations.RemoveField(
            model_name='ratedifferential',
            name='insurance_plan',
        ),
        migrations.RemoveField(
            model_name='subcountyrate',
            name='insurance_plan',
        ),
    ]
