# Generated by Django 4.2 on 2023-04-16 16:55

import django.contrib.postgres.fields
from django.db import migrations
import ext.models


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0006_remove_insuranceofferarea_beta_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitDiscount1',
            fields=[
                ('id', ext.models.SmallFloatField(primary_key=True, serialize=False)),
                ('enterprise_discount_factor', django.contrib.postgres.fields.ArrayField(base_field=ext.models.SmallFloatField(), size=48)),
            ],
        ),
    ]
