# Generated by Django 4.2 on 2023-04-16 18:13

import django.contrib.postgres.fields
from django.db import migrations, models
import ext.models


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0007_unitdiscount1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beta1',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('draw', django.contrib.postgres.fields.ArrayField(base_field=ext.models.SmallFloatField(), size=1000)),
            ],
        ),
    ]
