# Generated by Django 4.2.1 on 2023-06-17 19:58

from django.db import migrations, models
import ext.models


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0007_arearate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchmarkRevenue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('state_id', models.SmallIntegerField()),
                ('county_code', models.SmallIntegerField()),
                ('crop', models.SmallIntegerField()),
                ('practice', models.SmallIntegerField()),
                ('crop_year', models.SmallIntegerField()),
                ('benchmark_revenue', ext.models.SmallFloatField()),
            ],
            options={
                'db_table': 'ext_govpmt_benchmark_revenue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyaPost',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('crop_year', models.SmallIntegerField()),
                ('forecast_month', models.CharField(max_length=8)),
                ('wasde_release_date', models.DateField(verbose_name='WASDE release date')),
                ('corn_price', models.FloatField(null=True)),
                ('beans_price', models.FloatField(null=True)),
                ('wheat_price', models.FloatField(null=True)),
                ('corn_pct_locked', models.FloatField(null=True)),
                ('beans_pct_locked', models.FloatField(null=True)),
                ('wheat_pct_locked', models.FloatField(null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='SoybeanInsTypeForState',
        ),
    ]
