# Generated by Django 4.2 on 2023-04-16 18:59

import django.contrib.postgres.fields
from django.db import migrations, models
import ext.models


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0008_beta1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsidy1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('subsidy', django.contrib.postgres.fields.ArrayField(base_field=ext.models.SmallFloatField(), size=8)),
            ],
        ),
    ]
