# Generated by Django 4.2.2 on 2023-06-19 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0008_benchmarkrevenue_myapost_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyaPostEstimate',
        ),
    ]
