# Generated by Django 4.2.2 on 2023-06-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0009_delete_myapostestimate'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuturesContract',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=8)),
                ('croptype', models.CharField(max_length=10)),
                ('exchange', models.CharField(max_length=6)),
                ('futures_month', models.CharField(max_length=8)),
                ('contract_end_date', models.DateField()),
                ('market_crop_type_id', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
    ]
