# Generated by Django 4.2 on 2023-04-16 20:10

from django.db import migrations
import ext.models


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0009_subsidy1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baserate',
            old_name='coverage_level',
            new_name='reference_yield',
        ),
        migrations.AddField(
            model_name='baserate',
            name='reference_yield_prior',
            field=ext.models.SmallFloatField(default=0),
            preserve_default=False,
        ),
    ]
