# Generated by Django 4.2 on 2023-04-16 21:00

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import ext.models


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0010_rename_coverage_level_baserate_reference_yield_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseRate1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_code', models.SmallIntegerField()),
                ('practice', models.SmallIntegerField()),
                ('refyield', django.contrib.postgres.fields.ArrayField(base_field=ext.models.SmallFloatField(), size=2)),
                ('refrate', django.contrib.postgres.fields.ArrayField(base_field=ext.models.SmallFloatField(), size=2)),
                ('exponent', django.contrib.postgres.fields.ArrayField(base_field=ext.models.SmallFloatField(), size=2)),
                ('fixedrate', django.contrib.postgres.fields.ArrayField(base_field=ext.models.SmallFloatField(), size=2)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.commodity')),
                ('commodity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.commoditytype')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.state')),
            ],
        ),
    ]
