# Generated by Django 4.2.6 on 2023-10-13 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0010_futurescontract'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'managed': False, 'ordering': ['institution']},
        ),
    ]
