# Generated by Django 4.2 on 2023-04-16 22:24

from django.db import migrations, models
import ext.models


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0011_baserate1'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboRevenueFactor1',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('std_deviation_qty', ext.models.SmallFloatField()),
                ('mean_qty', ext.models.SmallFloatField()),
            ],
        ),
    ]
