# Generated by Django 4.2.6 on 2023-10-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0011_alter_budget_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvDiscoveryPrices',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('crop_year', models.SmallIntegerField()),
                ('county_code', models.SmallIntegerField()),
                ('market_crop_type_id', models.IntegerField()),
                ('priced_on', models.DateField()),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'ext_harv_discovery_prices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjDiscoveryPrices',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('crop_year', models.SmallIntegerField()),
                ('county_code', models.SmallIntegerField()),
                ('market_crop_type_id', models.IntegerField()),
                ('priced_on', models.DateField()),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'ext_proj_discovery_prices',
                'managed': False,
            },
        ),
    ]
