# Generated by Django 4.2 on 2023-04-16 23:38

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import ext.models


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0012_comborevenuefactor1'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateDifferential1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_code', models.SmallIntegerField()),
                ('coverage_level', ext.models.SmallFloatField()),
                ('rate_differential_factor', django.contrib.postgres.fields.ArrayField(base_field=ext.models.SmallFloatField(), size=16)),
                ('practice', models.SmallIntegerField()),
                ('high_risk', models.BooleanField()),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.commodity')),
                ('commodity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.commoditytype')),
                ('coverage_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.coveragetype')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.state')),
            ],
        ),
    ]
