# Generated by Django 4.2 on 2023-04-17 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0013_ratedifferential1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratedifferential1',
            name='coverage_level',
        ),
        migrations.RemoveField(
            model_name='ratedifferential1',
            name='coverage_type',
        ),
    ]
