# Generated by Django 4.2 on 2023-04-17 00:30

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import ext.models


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0014_remove_ratedifferential1_coverage_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseFactor1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_code', models.SmallIntegerField()),
                ('enterprise_residual_factor_r', django.contrib.postgres.fields.ArrayField(base_field=ext.models.SmallFloatField(), size=16)),
                ('enterprise_residual_factor_y', django.contrib.postgres.fields.ArrayField(base_field=ext.models.SmallFloatField(), size=16)),
                ('practice', models.SmallIntegerField()),
                ('high_risk', models.BooleanField()),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.commodity')),
                ('commodity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.commoditytype')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.state')),
            ],
        ),
    ]
