# Generated by Django 4.2 on 2023-04-17 14:00

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import ext.models


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0015_enterprisefactor1'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionRate1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_code', models.SmallIntegerField()),
                ('option_rate', django.contrib.postgres.fields.ArrayField(base_field=ext.models.SmallFloatField(), size=2)),
                ('practice', models.SmallIntegerField()),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.commodity')),
                ('commodity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.commoditytype')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.state')),
            ],
        ),
    ]
