# Generated by Django 4.2 on 2023-04-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0016_optionrate1'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='arearate',
            index=models.Index(fields=['area_rate_id'], name='ext_arearat_area_ra_da7e1d_idx'),
        ),
    ]
