# Generated by Django 4.2 on 2023-04-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0017_arearate_ext_arearat_area_ra_da7e1d_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='areacoveragelevel',
            index=models.Index(fields=['insurance_offer_id'], name='ext_areacov_insuran_705555_idx'),
        ),
    ]
