# Generated by Django 4.2 on 2023-04-17 14:28

import django.contrib.postgres.fields
from django.db import migrations, models
import ext.models


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0018_areacoveragelevel_ext_areacov_insuran_705555_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaRate1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_offer_id', models.IntegerField()),
                ('price_volatility_factor', models.IntegerField()),
                ('base_rate', django.contrib.postgres.fields.ArrayField(base_field=ext.models.SmallFloatField(), size=5)),
            ],
        ),
        migrations.AddIndex(
            model_name='arearate1',
            index=models.Index(fields=['insurance_offer_id', 'price_volatility_factor'], name='ext_arearat_insuran_43bb2b_idx'),
        ),
    ]
