# Generated by Django 4.2 on 2023-04-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0019_arearate1_arearate1_ext_arearat_insuran_43bb2b_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arearate1',
            name='price_volatility_factor',
            field=models.IntegerField(null=True),
        ),
    ]
