# Generated by Django 4.2 on 2023-04-17 19:46

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import ext.models


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0020_alter_arearate1_price_volatility_factor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaRate2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_offer_id', models.IntegerField()),
                ('price_volatility_factor', models.IntegerField(null=True)),
                ('county_code', models.SmallIntegerField()),
                ('practice', models.SmallIntegerField()),
                ('base_rate', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=ext.models.SmallFloatField(), size=None), size=None)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.commodity')),
                ('commodity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.commoditytype')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.state')),
            ],
        ),
        migrations.AddIndex(
            model_name='arearate2',
            index=models.Index(fields=['insurance_offer_id', 'price_volatility_factor'], name='ext_arearat_insuran_dae25e_idx'),
        ),
    ]
