# Generated by Django 4.2 on 2023-04-18 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0022_chessboard'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='arearate2',
            name='ext_arearat_insuran_dae25e_idx',
        ),
        migrations.RemoveField(
            model_name='arearate2',
            name='insurance_offer_id',
        ),
        migrations.AddIndex(
            model_name='arearate2',
            index=models.Index(fields=['state_id', 'county_code', 'commodity_id', 'commodity_type_id', 'practice', 'price_volatility_factor'], name='ext_arearat_state_i_c22b2e_idx'),
        ),
    ]
