# Generated by Django 4.2 on 2023-04-18 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0023_remove_arearate2_ext_arearat_insuran_dae25e_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='arearate2',
            name='ext_arearat_state_i_c22b2e_idx',
        ),
        migrations.AddField(
            model_name='arearate2',
            name='insurance_plan',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ext.insuranceplan'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='arearate2',
            index=models.Index(fields=['insurance_plan_id', 'state_id', 'county_code', 'commodity_id', 'commodity_type_id', 'practice', 'price_volatility_factor'], name='ext_arearat_insuran_988497_idx'),
        ),
    ]
