# Generated by Django 4.2 on 2023-04-18 17:59

from django.db import migrations, models
import django.db.models.deletion
import ext.models


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0024_remove_arearate2_ext_arearat_state_i_c22b2e_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_code', models.SmallIntegerField()),
                ('practice', models.SmallIntegerField()),
                ('expected_yield', ext.models.SmallFloatField(null=True)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.commodity')),
                ('commodity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.commoditytype')),
                ('insurance_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.insuranceplan')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext.state')),
            ],
        ),
        migrations.DeleteModel(
            name='ChessBoard',
        ),
    ]
