# Generated by Django 4.2 on 2023-04-18 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0026_delete_arearate_delete_arearate1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AreaRate2',
            new_name='AreaRate',
        ),
        migrations.RenameModel(
            old_name='BaseRate1',
            new_name='BaseRate',
        ),
        migrations.RenameModel(
            old_name='Beta1',
            new_name='Beta',
        ),
        migrations.RenameModel(
            old_name='ComboRevenueFactor1',
            new_name='ComboRevenueFactor',
        ),
        migrations.RenameModel(
            old_name='EnterpriseFactor1',
            new_name='EnterpriseFactor',
        ),
        migrations.RenameModel(
            old_name='OptionRate1',
            new_name='OptionRate',
        ),
        migrations.RenameModel(
            old_name='RateDifferential1',
            new_name='RateDifferential',
        ),
        migrations.RenameModel(
            old_name='Subsidy1',
            new_name='Subsidy',
        ),
        migrations.RenameModel(
            old_name='UnitDiscount1',
            new_name='UnitDiscount',
        ),
        migrations.RenameIndex(
            model_name='arearate',
            new_name='ext_arearat_insuran_732747_idx',
            old_name='ext_arearat_insuran_e960c0_idx',
        ),
    ]
