# Generated by Django 4.2 on 2023-04-18 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0027_rename_arearate2_arearate_rename_baserate1_baserate_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Price',
            new_name='ExpectedYield',
        ),
        migrations.DeleteModel(
            name='AreaCoverageLevel',
        ),
    ]
