# Generated by Django 4.2 on 2023-04-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0028_rename_price_expectedyield_delete_areacoveragelevel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcountyrate',
            name='practice',
        ),
        migrations.AddIndex(
            model_name='baserate',
            index=models.Index(fields=['state_id', 'county_code', 'commodity_id', 'commodity_type_id', 'practice'], name='ext_baserat_state_i_2cffdf_idx'),
        ),
        migrations.AddIndex(
            model_name='county',
            index=models.Index(fields=['state_id', 'code'], name='ext_county_state_i_28a433_idx'),
        ),
        migrations.AddIndex(
            model_name='enterprisefactor',
            index=models.Index(fields=['state_id', 'county_code', 'commodity_id', 'commodity_type_id', 'practice'], name='ext_enterpr_state_i_0a2f14_idx'),
        ),
        migrations.AddIndex(
            model_name='expectedyield',
            index=models.Index(fields=['state_id', 'county_code', 'commodity_id', 'commodity_type_id'], name='ext_expecte_state_i_1c1029_idx'),
        ),
        migrations.AddIndex(
            model_name='insuranceofferent',
            index=models.Index(fields=['state_id', 'county_code', 'commodity_id', 'commodity_type_id', 'practice'], name='ext_insuran_state_i_75adcb_idx'),
        ),
        migrations.AddIndex(
            model_name='optionrate',
            index=models.Index(fields=['state_id', 'county_code', 'commodity_id', 'commodity_type_id', 'practice'], name='ext_optionr_state_i_1dd425_idx'),
        ),
        migrations.AddIndex(
            model_name='practice',
            index=models.Index(fields=['commodity_id', 'code'], name='ext_practic_commodi_e77c55_idx'),
        ),
        migrations.AddIndex(
            model_name='ratedifferential',
            index=models.Index(fields=['state_id', 'county_code', 'commodity_id', 'commodity_type_id', 'practice'], name='ext_ratedif_state_i_305b9e_idx'),
        ),
        migrations.AddIndex(
            model_name='subcountyrate',
            index=models.Index(fields=['state_id', 'county_code', 'subcounty_id', 'commodity_id', 'commodity_type_id'], name='ext_subcoun_state_i_08768a_idx'),
        ),
    ]
