# Generated by Django 4.2 on 2023-04-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0029_remove_subcountyrate_practice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitdiscount',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
