# Generated by Django 4.2 on 2023-04-18 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0030_alter_unitdiscount_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insuranceofferent',
            old_name='beta_id',
            new_name='beta1_id',
        ),
        migrations.RenameField(
            model_name='insuranceofferent',
            old_name='unit_discount_id',
            new_name='unit1_discount_id',
        ),
    ]
