# Generated by Django 4.2 on 2023-04-18 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0031_rename_beta_id_insuranceofferent_beta1_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceofferent',
            name='beta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ext.beta'),
        ),
        migrations.AddField(
            model_name='insuranceofferent',
            name='unit_discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ext.unitdiscount'),
        ),
    ]
