# Generated by Django 4.2 on 2023-04-18 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0032_insuranceofferent_beta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuranceofferent',
            name='beta1_id',
        ),
        migrations.RemoveField(
            model_name='insuranceofferent',
            name='unit1_discount_id',
        ),
    ]
