# Generated by Django 4.2 on 2023-04-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0033_remove_insuranceofferent_beta1_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcountyrate',
            name='high_risk',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
